application: minsub-portfolio
version: 1
runtime: php
api_version: 1
threadsafe: true

handlers:
- url: /(.*\.(jpeg|jpg|png|gif))
  static_files: \1
  mime_type: (image/jpg|image/png|image/gif)
  upload: (.*\.(jpeg|jpg|png|gif))

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /fonts
  static_dir: fonts

- url: /.*
  script: blog.html
